### ISSUE TITLE
Riot client does not always start activated

### ISSUE THREAD

**Issue by michalis97500** [adeci/LoLogin#1]
If the riot client is not in front of any other applications the program fails to enter the data. 
I suggest bringing the client to front eg. Doing so seems to fix the issues however I am having trouble turning the py file to an exe

while True:
        if checkIfProcessRunning('RiotClient'):
            win = gw.getWindowsWithTitle('Riot Client Main')[0] 
            win.activate()
            //rest of code

**Comment by adeci** [comment]
Hey, yes I actually fixed this in a revised version but I haven't uploaded it yet. Checking for running id can get messy so the solution I found was just to call riot client to open as this brings it to the front.

I packaged the code with py installer but you need to include some files in the compilation. I will update this soon.

**Comment by michalis97500** [comment]
Would you mind sharing the compilation command so I can compile this myself too?  Thanks for your fast reply!

**Comment by adeci** [comment]
Sorry for the delay, I was at work. 
I uploaded the updated program and used your solution utilizing pygetwindow, thank you for the suggestion!
Here is the command I use when compiling:

pyinstaller -w --icon icon.ico --add-data "icon.png;." --add-data "azure.tcl;." --add-data "accounts.csv;." --add-data "theme;theme" LoLogin.py

This will give you a 'dist' folder inside of your compilation folder and within that is the final product - the LoLogin folder. Put it wherever you want and make a shortcut to the exe within.

Make sure within the folder you are compiling from you have the LoLogin.py, azure.tcl, themes folder,  icon.ico, icon.png, and accounts.csv. On a side note, pyinstaller has been flakey when compiling from inside my windows drive with this error:
PermissionError: [Errno 13] Permission denied
So I have been compiling from an external drive in my PC (ie - move your compilation folder to some other non windows critical drive and issue command from there.)

**Comment by michalis97500** [comment]
Thank you so much for your help!
